### PR TITLE
Adds github actions and fixes balena.yml

### PR DESCRIPTION
**Pull request by Bucknalla**
Change-type: minor
Signed-off-by: Alex Bucknall <alex.bucknall@gmail.com>

### CODE REVIEW

**Comment by Bucknalla** [comment]
@tjvantoll @bsatrom to merge these changes and automate the release of this block to balenaHub, you'll need to generate an API key from the blues wireless balenaCloud account and add it to the secrets on this repo as `BALENA_API_KEY`. You'll also need to create 2 more blocks for `blues_wireless/notecard-armv7hf` and `blues_wireless/notecard-amd64` if you want to support those architectures 😄 Let me know if I can help anywhere or if that's not clear!

**Comment by mpous** [comment]
I'm going to test the block on Raspberry Pi 3 (armv7) and Raspberry Pi Zero (armv6) to confirm that it works on these devices types and we can generate the newer blocks.

**Comment by tjvantoll** [comment]
Thanks for the help @Bucknalla! I’m going to merge this in and then work on generating those other blocks later today. I’ll let you know if I hit any other problems.

**Comment by mpous** [comment]
@tjvantoll tested pi3 and pi1 successfully so feel free to create the other blocks `armv7` and `armv6`. However `amd64` it's not necessary!

**Pull request merged**
